# Generated by Django 5.1.1 on 2025-01-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vetbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("photos_paths", models.JSONField(blank=True, null=True)),
                ("animal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="animals.animal")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationOthers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vaccine", models.CharField(max_length=20)),
                ("series", models.CharField(max_length=20)),
                ("expiration_date", models.DateField()),
                ("vaccination_clinic", models.CharField(max_length=20)),
                ("date_of_vaccination", models.DateField()),
                ("vaccine_expiration_date", models.DateField()),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_vaccination_against_rabies",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationAgainstRabies",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vaccine", models.CharField(max_length=20)),
                ("series", models.CharField(max_length=20)),
                ("expiration_date", models.DateField()),
                ("vaccination_clinic", models.CharField(max_length=20)),
                ("date_of_vaccination", models.DateField()),
                ("vaccine_expiration_date", models.DateField()),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_other_vaccinations",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clinic", models.CharField(max_length=20)),
                ("registration_number", models.CharField(max_length=35)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_registration",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Identification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chip_number", models.CharField(max_length=35)),
                ("clinic", models.CharField(max_length=20)),
                ("chip_installation_location", models.CharField(max_length=20)),
                ("date", models.DateField()),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_identification",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EctoparasiteTreatment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("drug", models.CharField(max_length=35)),
                ("date", models.DateField()),
                ("clinic", models.CharField(max_length=35)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_ectoparasite_treatment",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deworming",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("drug", models.CharField(max_length=35)),
                ("date", models.DateField()),
                ("clinic", models.CharField(max_length=35)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_deworming",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalExamination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("result", models.TextField(max_length=20)),
                ("files_ids", models.JSONField(blank=True, null=True)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_examinations",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("breed", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                ("special_marks", models.CharField(max_length=20)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_additional_description",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
    ]
