# Generated by Django 5.1.1 on 2025-02-03 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vetbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("files_ids", models.JSONField(blank=True, null=True)),
                ("animal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="animals.animal")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="VetbookFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_file_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vetbooks",
                    models.ManyToManyField(blank=True, related_name="vetbook_related_files", to="vetbooks.vetbook"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vetpass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbooks_vetpass",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationOthers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vaccine", models.CharField(blank=True, max_length=20, null=True)),
                ("series", models.CharField(blank=True, max_length=20, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("vaccination_clinic", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_vaccination", models.DateField(blank=True, null=True)),
                ("vaccine_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_vaccination_against_rabies",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationAgainstRabies",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vaccine", models.CharField(blank=True, max_length=20, null=True)),
                ("series", models.CharField(blank=True, max_length=20, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("vaccination_clinic", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_vaccination", models.DateField(blank=True, null=True)),
                ("vaccine_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_other_vaccinations",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clinic", models.CharField(blank=True, max_length=20, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_registration",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Identification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chip_number", models.CharField(blank=True, max_length=35, null=True)),
                ("clinic", models.CharField(blank=True, max_length=20, null=True)),
                ("chip_installation_location", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_identification",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EctoparasiteTreatment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("drug", models.CharField(blank=True, max_length=35, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("clinic", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_ectoparasite_treatment",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deworming",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("drug", models.CharField(blank=True, max_length=35, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("clinic", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_deworming",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalExamination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(blank=True, null=True)),
                ("result", models.TextField(blank=True, max_length=20, null=True)),
                ("files_ids", models.JSONField(blank=True, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_examinations",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalDescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("breed", models.CharField(blank=True, max_length=20, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("special_marks", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "vetpass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetpass_additional_description",
                        to="vetbooks.vetpass",
                    ),
                ),
            ],
        ),
    ]
