# Generated by Django 5.1.1 on 2025-02-25 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vetbooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clinic_name", models.CharField(max_length=20)),
                ("visit_date", models.DateField()),
                ("complaints", models.TextField(max_length=35)),
                ("doctor_report", models.TextField(blank=True, max_length=255, null=True)),
                ("examination_files_ids", models.JSONField(blank=True, null=True)),
                ("other_files_ids", models.JSONField(blank=True, null=True)),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_appointments",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_appointment_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vetbooks",
                    models.ManyToManyField(
                        blank=True, related_name="appointment_related_files", to="vetbooks.appointment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("medication", models.CharField(max_length=20)),
                ("dosage", models.CharField(max_length=20)),
                ("frequency", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "vetbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_treatments",
                        to="vetbooks.vetbook",
                    ),
                ),
            ],
        ),
    ]
