# Generated by Django 5.1.1 on 2025-01-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vetbooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="vetbook",
            old_name="photos_paths",
            new_name="files_ids",
        ),
        migrations.CreateModel(
            name="VetbookFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vetbook_file_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vetbooks",
                    models.ManyToManyField(blank=True, related_name="vetbook_related_files", to="vetbooks.vetbook"),
                ),
            ],
        ),
    ]
