# Generated by Django 5.1.1 on 2025-01-31 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vetbooks", "0002_rename_photos_paths_vetbook_files_ids_vetbookfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetbook",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vetbook",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
