# Generated by Django 5.1.1 on 2025-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vetbooks", "0003_clinicalexaminationfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmentfile",
            old_name="vetbooks",
            new_name="appointment",
        ),
    ]
