# Generated by Django 5.1.1 on 2024-11-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('perks', models.TextField(choices=[('PH', 'Homeless Helper'), ('HH', 'Pers Helper'), ('VR', 'Volunteer'), ('SW', 'Shelter Worker'), ('PO', 'Pet Owner'), ('VT', 'Vet'), ('DH', 'Dog Handler'), ('ZP', 'Zoopsychologist')], default='PH')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
