# Generated by Django 5.1.1 on 2024-11-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_question_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("score", models.SmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
