version: "3.7"
services:

  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - backend-prod
      - frontend-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
    networks:
      - prod

  backend-prod:
    container_name: "backend-prod:8000"
    image: backend-prod
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - prod

  frontend-prod:
    container_name: "frontend-prod:5173"
    image: frontend-prod
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    networks:
      - prod
      
networks:
  prod:
    driver: bridge
