version: "3.7"
services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
       - ./nginx_conf/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  # application service
  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - custom


networks:
  custom:
    driver: bridge