version: "3.7"
services:

  app:
    container_name: "backend-prod"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
