version: "3.7"
services:

  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
    networks:
      - prod

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - prod
    depends_on:
      - db
      - redis
    restart: always

  db:
    container_name: db
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - prod
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - prod
    volumes:
      - redis_data:/data

networks:
  prod:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
