[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]
exclude = [
    "venv",
    ".venv",
    "migrations",
    "*/migrations/*",
    "*/venv/*",
    "*/.venv/*"
]

[tool.isort]
profile = "black"
skip = [
    "venv",
    ".venv",
    "migrations",
    "*/migrations/*",
    "*/venv/*",
    "*/.venv/*"
]

[tool.black]
line-length = 120
exclude = '''
/(
    .*?venv
    |migrations
    |.*/migrations/.*
)/
'''
