[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]
exclude = ["venv", "migrations", "*/migrations/*"]

[tool.isort]
profile = "black"
skip = ["venv", "migrations", "*/migrations/*"]

[tool.black]
line-length = 120
exclude = '''
/(
    venv
    |migrations
    |.*/migrations/.*
)/
'''
