# Generated by Django 5.1.1 on 2025-01-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="name",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="animal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_animals", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
