# Generated by Django 5.1.1 on 2024-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_messagefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("IN_PROGRESS", "InProgress"), ("COMPLETED", "Completed")],
                default="IN_PROGRESS",
                max_length=50,
            ),
        ),
    ]
