# Generated by Django 5.1.1 on 2024-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0006_message_user_id_questionreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionreview",
            name="score",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="questionreview",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
