# Generated by Django 5.1.1 on 2024-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0007_alter_questionreview_score_alter_questionreview_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="vet_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
