# Generated by Django 5.1.1 on 2025-03-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialist_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="file_ids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="specialistdocument",
            name="specialist",
        ),
        migrations.AddField(
            model_name="specialistdocument",
            name="specialist",
            field=models.ManyToManyField(blank=True, related_name="related_documents", to="specialist_info.specialist"),
        ),
    ]
