# Generated by Django 5.1.1 on 2024-12-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freevet_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code_sent_time', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
