name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      
jobs:
  checks-source-code:
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make deps

      - name: Run linters
        run: make lint

  deploy:
    needs: checks-source-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PASSWORD }}" | ssh-add ~/.ssh/id_rsa


      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no s_makarov_de_gmail_com@34.32.159.135 << 'EOF'

          cd /home/app/prod/back || { git clone https://github.com/tail-book/freevet-backend.git /home/app/prod/back; cd /home/app/prod/back; }

          git remote set-url origin https://github.com/tail-book/freevet-backend.git
          export GIT_TOKEN="${{ secrets.GIT_TOKEN }}"
          git config --global credential.helper '!f() { echo "username=AlexKrutskikh"; echo "password=$GIT_TOKEN"; }; f'

          git fetch origin dev
          git reset --hard origin/dev

          docker-compose pull
          docker-compose -f docker-compose-prod.yaml up -d --build
          EOF
