name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      
jobs:
  checks-source-code:
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: make deps

      - name: Run linters
        run: make lint

  deploy:
    needs: checks-source-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no freevet@34.32.159.135 << 'EOF'
    
            cd /home/app/prod/back || { git clone https://github.com/tail-book/freevet-backend.git /home/app/prod/back; cd /home/app/prod/back; }

            git remote set-url origin https://github.com/tail-book/freevet-backend.git
            echo 'https://AlexKrutskikh:${{ secrets.GIT_TOKEN }}@github.com/tail-book/freevet-backend.git' > ~/.git-credentials
            git config --global credential.helper store

            git fetch origin dev
            git reset --hard origin/dev
          
            docker-compose down
            docker-compose -f docker-compose-prod.yaml up --build -d
          EOF
