name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Server Access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add GitHub to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no kruts@34.34.29.241 "
            cd /home/kruts/FreeVetbackend &&
            git remote set-url origin git@github.com:AlexKrutskikh/freevet-backend.git &&
            git fetch origin dev &&
            git reset --hard origin/dev &&
            docker-compose down &&
            docker-compose up -d --build
          "
