name: Deploy to Server

on:
  workflow_run:
    workflows: ["check.yml"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          ssh-key-passphrase: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no kruts@34.34.29.241 "
            cd /home/kruts/FreeVetbackend &&
            git pull &&
            docker-compose down &&
            docker-compose up -d --build
          "
